### ISSUE TITLE
Idea: More insightful graphical representation

### ISSUE THREAD

**Issue by probonopd** [bengtmartensson/IrScrutinizer#162]
Probably many users of IrScrutinizer are not just interested in getting the codes to work _per se_ but also want to learn something about their meaning along the way. For this, I would find it useful if the graphical representation could explain a bit more about the decoded protocols, like in the example below from the open source [PulseView](https://sigrok.org/wiki/PulseView) software.

![PulseView](https://cloud.githubusercontent.com/assets/2480569/21352438/bc58188a-c6c1-11e6-86f3-99c65ed92d0c.png)

The above was made with a TSOP attached to a 6 EUR logic analyzer from China and [PulseView.AppImage](https://bintray.com/probono/AppImages/PulseView#files).

Also, I wonder if the protocol decoders (and possibly more) could be shared between the two projects.

**Comment by bengtmartensson** [comment]
The idea of annotating/decorating the plot with decoder/IRP information (as well as breaking-up non-interlacing protocols like the bi-phase (Manchester) protocols like RC5, the red row in the picture above) is certainly very attractive. But also quite a lot of work. 

Breaking up non-interlaced protocols is actually pretty much a different task from the IRP interpretation. (Note: Background colors can be used to (space savingly) indicate 0 or 1.)

Note that this should be make in the content of [IrpTransmogrifier](https://github.com/bengtmartensson/IrpTransmogrifier), which will replace IrpMaster, DecodeIR and the Analyzer.

(BTW, I tried PulseView. The program is completely free from non-trivial user documentation. Tried to have it to display a generated CVS. Core dump. Not very impressed...)

Thank you very much for the suggestions!

**Comment by bengtmartensson** [comment]
Must wait for IrpTransmogrifer migration, a.k.a. Milestone Transmogrifier.

**Comment by probonopd** [comment]
> BTW, I tried PulseView. The program is completely free from non-trivial user documentation.

That is probably because it is "just" the GUI for [Sigrok](https://sigrok.org/wiki/Main_Page) which is well documented imho.

**Comment by bengtmartensson** [comment]
It would also be useful and natural to visualize what the repeat finder has done. Possibly an interactive toggle that toggles between repeat-reduced and original signal.

**Comment by bengtmartensson** [comment]
"Un-On Hold"-ed" with IrScrutinizer 2.0.1!  I really like the idea, in particular if it can be combined with (interactive) debugging of (non-)decodes. But is yet unclear to me exactly how it can be implemented.
