### ISSUE TITLE
Overlapping text in signal graphic

### ISSUE THREAD

**Issue by probonopd** [bengtmartensson/IrScrutinizer#291]
In the 1.3.1dev AppImage on Xubuntu 18.04, entering and scrutinizing

`+8000, -8000, +2000, -1000, +1000, -1000, +2000, -1000, +2000, -1000, +1000, -1000, +1000, -1000, +1000, -1000, +1000, -1000, +2000, -1000, +2000, -1000, +1000, -1000, +2000, -1000, +1000, -2000`

I get

![](https://user-images.githubusercontent.com/2480569/61168478-4b379500-a53e-11e9-9425-216135c9d6d3.png)

The last number is not displayed clearly because of overlapping text.

**Comment by bengtmartensson** [comment]
Thank you for the report. Although it is hard to argue that the behavior is correct, it is not a KO-issue. There are a few issues, an missing features with the plotter, this is not the most urgent :-).

**Comment by probonopd** [comment]
Indeed :)
