### ISSUE TITLE
Misleading repo name

### ISSUE THREAD

**Issue by seanyoung** [bengtmartensson/IrScrutinizer#359]
The README.md says:

> Repository
> 
> The GitHub repository name (harctoolboxbundle) is now misleading. It has historic reasons. Since it is widely spread, for example as a download address, I have decided not to change it.

github repositories can be renamed and the old name will automatically redirect to the new name. See https://help.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by bengtmartensson** [comment]
Hmm, I was not aware of that (obviously). I have rename as suggested. Thanx a lot!
