### ISSUE TITLE
Issue with G.I.4DTV protocol.

### ISSUE THREAD

**Issue by kdschlosser** [bengtmartensson/IrScrutinizer#385]
OK so now I am running the latest version. :smile:

the notation for this protocol is 
```
{37.3k,992}<1,-1|1,-3>(5,-2,F:6,D:2,C0:1,C1:1,C2:1,C3:1,1,-60)* { C0=D:1:2 + #(F&25) + #(D&1), C1=D:1:2 + #(F&43) + #(D&3), C2=D:1:2 + #(F&22) + #(D&3), C3=D:1:2 + #(F&44) + #(D&2) }[D:0..7, F:0..63]
```

so that makes the following form that notation.
frequency 37300
bit_order lsb
mark_0 992
space_0 -992
mark_1 992
space_1 -2976
header_mark 4960
header_space -1984
footer_mark 992
footer_space -59520

I generated this code using you app
D=7
F=26
```
+4960,-1984,+992,-992,+992,-2976,+992,-992,+992,-2976,+992,-2976,+992,-992,+992,-2976,+992,-2976,+992,-992,+992,-2976,+992,-2976,+992,-2976,+992,-59520
```

when i break the code down
```
+4960,-1984, header

function
+992,-992,  0
+992,-2976,  1
+992,-992,  0
+992,-2976,  1
+992,-2976,  1
+992,-992,  0

device
+992,-2976,  1
+992,-2976,  1


checksum
+992,-992,  0
+6992,-2976,  1
+992,-2976,  1
+992,-2976,  1

+992,-59520 footer
]
```

I am not exactly sure how you are managing to get device numbers 1-7 from a 2 bit number. it could be a typo and the device numbers are only supposed to range from 0-3

**Comment by bengtmartensson** [comment]
The documentation for the protocol says

>  {37.3k,992}<1,-1|1,-3>(5,-2,F:6,D:2,C0:1,C1:1,C2:1,C3:1,1,-60)*
{
C0=D:1:2 + #(F&25) + #(D&1),
C1=D:1:2 + #(F&43) + #(D&3),
C2=D:1:2 + #(F&22) + #(D&3),
C3=D:1:2 + #(F&44) + #(D&2)
}[D:0..7, F:0..63]

> This is a moderately robust protocol, but spurious decodes are still possible. Unit (device) numbers from 0 to 7 are supported. The check sum C is a Hamming Code, which can correct single bit errors. D:1:2 is encoded in the checksum. See [forum thread](http://www.hifi-remote.com/forums/viewtopic.php?p=103934#103934).

which answers the question. See the quoted thread for more information. If questions or discussions remain, please direct them to the [JP1-forum](http://hifi-remote.com/forums);  the real experts for this protocol sit there,
