### ISSUE TITLE
Remove RemoteMaster import and export

### ISSUE THREAD

**Issue by bengtmartensson** [bengtmartensson/IrScrutinizer#400]
Current RMIR/RemoteMaster supports Girr export with very few fails, which makes RemoteMaster import superfluous. It basically only succeeds in simple cases.

Also RemoteMaster export has no meaning since RMIR can import girr.

Any comments?

**Comment by lpmlpm** [comment]
OK and please update the documentation. The Help file in IRScrutinizer still mentioned RM functions. Also, the docs at http://www.harctoolbox.org/IrScrutinizer.html still say import/export for RemoteMaster is supported.
