### ISSUE TITLE
Kubuntu installation AppImage problem

### ISSUE THREAD

**Issue by morusa** [bengtmartensson/IrScrutinizer#404]
hi,

"appimage" is supposed to simplify distribution, but it doesn't work on kubuntu :(

$ sudo ./IrScrutinizer-2.3.0-x86_64.appimage 
[sudo] password for user: ***
/tmp/.mount_IrScrumqtoPi/AppRun: 31: exec: IrScrutinizer-2.3.0-x86_64.appimage: not found

**Comment by bengtmartensson** [comment]
chmod +x IrScrutinizer-2.3.0-x86_64.appimage

and do not use sudo.

**Comment by morusa** [comment]
thanks for answering. I already tried on another computer and the same:

$ chmod +x IrScrutinizer-2.3.0-x86_64.appimage 
$ ./IrScrutinizer-2.3.0-x86_64.appimage 
/tmp/.mount_IrScruVUmedI/AppRun: 31: exec: IrScrutinizer-2.3.0-x86_64.appimage: not found

**Comment by bengtmartensson** [comment]
What kubunto version are you using? Both "this" and the "other computer"?

**Comment by zarpli** [comment]
> hi,
> 
> "appimage" is supposed to simplify distribution, but it doesn't work on kubuntu :(

please update kubuntu to latest

**Comment by morusa** [comment]
I apologize, everything works fine in kubuntu 20.10

**Comment by bengtmartensson** [comment]
Ok, nice that it is working. Hope you will like IrScrutinizer.

But I would very much like to know if you have one or more kubunto versions (current or not) which will not run the AppImage.

**Comment by morusa** [comment]
IrScrutinizer is a powerful tool, thanks for the linux support!

I guarantee you the AppImage doesn't work on kubuntu 19.10, but on the latest one (19.20) it works great.

**Comment by morusa** [comment]
IrScrutinizer is a powerful tool, thanks for the linux support!

I guarantee you the AppImage doesn't work on kubuntu 19.10, but on the latest one (20.10) it works great.
