### ISSUE TITLE
Improve TV-B-gone export with new compression method

### ISSUE THREAD

**Issue by CustardFlan** [bengtmartensson/IrScrutinizer#405]
Hi!

I want some help there
IrScrutinizer export to TV-B-Gone C code works fine, but, in order to use these with the kit offered in Adafruit:
[(https://learn.adafruit.com/tv-b-gone-kit/design-notes)]
the export method needs to be updated, to compress the code with the method mentioned in the design notes

Following the instructions for making a usable TV Power or anything code for using in the kit, works, indeed, but i have already +200 power codes, and i want to export and integrate in my project with less pain and effort

I attach the steps for reproduce the compression method in the code, wish this gonna be hepful

`//original IrScrutinizer TV-B-Gone export

const struct powercode IrScrutinizer scrutinized signal PROGMEM = {
   freq_to_timerval(38380),
   {
      { 904, 451 },
      { 57, 57 },
      { 57, 57 },
      { 57, 57 },
      { 57, 57 },
      { 57, 57 },
      { 57, 57 },
      { 57, 57 },
      { 57, 57 },
      { 57, 169 },
      { 57, 169 },
      { 57, 169 },
      { 57, 169 },
      { 57, 169 },
      { 57, 169 },
      { 57, 169 },
      { 57, 169 },
      { 57, 169 },
      { 57, 57 },
      { 57, 169 },
      { 57, 57 },
      { 57, 57 },
      { 57, 57 },
      { 57, 169 },
      { 57, 57 },
      { 57, 57 },
      { 57, 169 },
      { 57, 57 },
      { 57, 169 },
      { 57, 169 },
      { 57, 169 },
      { 57, 57 },
      { 57, 169 },
      { 57, 3979 },
   }
};

//Entries count:
//34 Entries
//34 ENTRADAS

//grouped times organized by first column ascendant
0      { 57, 169 },
1     { 57, 3979 },
2     { 57, 57 },
3     { 904, 451 },	  

//times order	  
3
2
2
2
2
2
2
2
2
0
0
0
0
0
0
0
0
0
2
0
2
2
2
0
2
2
0
2
0
0
0
2
0
1

//To Binary
//a binario

11
10
10
10
10
10
10
10
10
00
00
00
00
00
00
00
00
00
10
00
10
10
10
00
10
10
00
10
00
00
00
10
00
01

//appending
//Concatenado
11101010101010101000000000000000000010001010100010100010000000100001

//dividing in 8 bit chunks
//separado en bloques de 8 bits

11101010 10101010 10000000 00000000 00001000 10101000 10100010 00000010 0001

//zero padding the final chunk
//con padding al final
11101010 10101010 10000000 00000000 00001000 10101000 10100010 00000010 00010000

//to decimal
//a decimal
234 170 128 0 8 168 162 2 16

//to hexadecimal
//a hexadecimal
0xea 0xaa 0x80 0x0 0x8 0xa8 0xa2 0x2 0x10

//make a table with these values
//tabla de codigos
0xEA,
0xAA,
0x80,
0x00,
0x08,
0xA8,
0xA2,
0x02,
0x10,

//The final C structure

const uint16_t code_ChnCsTimes[] = {
  57, 169,
  57, 3979,
  57, 57,
  904, 451,

};
const uint8_t code_ChnCsCodes[] = {
0xEA,
0xAA,
0x80,
0x00,
0x08,
0xA8,
0xA2,
0x02,
0x10,
};
const struct IrCode code_ChnCsCode = {
  freq_to_timerval(38380),
  34,             // # of pairs
  2,              // # of bits per index
  code_ChnCsTimes,
  code_ChnCsCodes
};`

Greets!

**Comment by bengtmartensson** [comment]
If someone can submit a fix I will be happy to test it (at least "plausiblity-test" it) and integrate. However, the task is just too peripheral to IrScrutinizer and my interests, so I will wontfix-close it.
