### ISSUE TITLE
irscrutinizer.sh bug: JVM_ARGS incorrectly appended to the arguments

### ISSUE THREAD

**Issue by Bananaman** [bengtmartensson/IrScrutinizer#421]
Hi Bengt!

I ran into this issue with openJDK 11 but suspect it happens with every Java runtime:

```
irscrutinizer --version
Error: Could not find or load main class 
Caused by: java.lang.ClassNotFoundException: 
```

Turns out that it's caused by the usage of `"${JAVA}" "${JVM_ARGS}" -classpath` in several of the calls.

If JVM_ARGS Is an empty or non-existent variable, then Java will think that the empty argument is the name of the class you want to launch.

There are two fixes for it:

- A: Always have a value for JVM_ARGS and pass it along just like you do now.
- or B: Change the `"${JVM_ARGS}"` to the correct way to expand multiple extra arguments. I forget how. I think it's `"${expression[@]}"`.

In fact, if I do that change, the launcher script works both with empty and with active (dpi scaling) JVM_ARGS.

Here's a patch that fixes it for me:

```patch
--- irscrutinizer.sh	2020-09-25 19:01:46.000000000 +0200
+++ /usr/local/share/irscrutinizer/irscrutinizer.sh	2021-05-01 02:42:30.387880885 +0200
@@ -78,7 +78,7 @@
     MESSAGE=$(echo ${MESSAGE} | sed -e "s/,$//")
     MESSAGEPRE="You are not a member of the group(s) "
     MESSAGETAIL=", so you will probably not have access to some devices.\nYou probably want to correct this. Otherwise, functionality will be limited.\n\nDepending on your operating system, the command for fixing this may be \"sudo usermod -aG $MESSAGE $USER\".\n\nProceed anyhow?"
-    if ! "${JAVA}" "${JVM_ARGS}" -classpath "${FATJAT}" \
+    if ! "${JAVA}" "${JVM_ARGS[@]}" -classpath "${FATJAT}" \
         org.harctoolbox.guicomponents.StandalonePopupAnnoyer "${MESSAGEPRE}${MESSAGE}${MESSAGETAIL}" "$@" ; then
         exit 1
     fi
@@ -89,4 +89,4 @@
 fi
 
 #exec "${JAVA}" ${LOAD_RXTX_PATH} ${RXTX_SERIAL_PORTS} -jar "${FATJAT}" --apphome "${IRSCRUTINIZERHOME}" "$@"
-exec "${JAVA}" ${JVM_ARGS} -jar "${FATJAT}" --apphome "${IRSCRUTINIZERHOME}" "$@"
+exec "${JAVA}" "${JVM_ARGS[@]}" -jar "${FATJAT}" --apphome "${IRSCRUTINIZERHOME}" "$@"
```

**Comment by bengtmartensson** [comment]
Hi Bananaman and thank you for your issue. Yes, it is a bug, but it has already been fixed in the [current code](https://github.com/bengtmartensson/IrScrutinizer/commits/master/src/main/config/irscrutinizer.sh), although it has not yet made it into an official release. (Feel free to use the [continuous build](https://github.com/bengtmartensson/IrScrutinizer/releases/tag/ci-build).)
