### ISSUE TITLE
Documentation improvement: User groups

### ISSUE THREAD

**Issue by Bananaman** [bengtmartensson/IrScrutinizer#422]
Hi, this is just a tiny suggestion about the Linux application launch message's warning about having to run `sudo usermodd -aG <all the groups and the username here>`. It would be good for new users if there's a note in the same message that tells them that they must log out and back in to make the group changes take effect.

**Comment by bengtmartensson** [comment]
Thank you very much for the suggestion; has been applied.

**Comment by Bananaman** [comment]
Looks great, and thank you very much for IrScrutinizer! 😄
