### ISSUE TITLE
IRDB (RemoteLocator) is very outdated

### ISSUE THREAD

**Issue by sandorex** [bengtmartensson/IrScrutinizer#508]
I recommend switching to jsdelivr at https://cdn.jsdelivr.net/gh/probonopd/irdb@master/codes or add option to specify url

RemoteLocator has been last updated `Generated by bengt on 2023-03-27_21:38:38`

**Comment by bengtmartensson** [comment]
@sandorex : FYI, `remotelocator.xml` was updated yesterday.
