### ISSUE TITLE
Improvement: Add more baud rate options for girs client

### ISSUE THREAD

**Issue by DjordjeMandic** [bengtmartensson/IrScrutinizer#534]
I'm running my m328p @ 8MHz and 115200/57600 baud is difficult to receive on chip itself. 
I prefer 250k / 500k or 1M baud for this scenario. 

Could you add more baud rate options?
![image](https://github.com/user-attachments/assets/9e066971-541e-4127-9b86-a2eeb59cc13a)

**Comment by bengtmartensson** [comment]
Thank you for the suggestion. I have done so; took all possible values from nrjavaserial. Hope it won't confuse anyone.

The recent [ci-build](https://github.com/bengtmartensson/IrScrutinizer/releases/tag/ci-build) contains the fix.
